### ISSUE TITLE
Class PhpQuery\PhpQuery not found

### ISSUE THREAD

**Issue by yeremi** [Bleez/Bleez-Correios#1]
Fatal Error Uncaught Error: 
Class PhpQuery\PhpQuery not found in vendor/bleez/correios/Model/Endereco/Correios.php:30

**Comment by cagartner** [comment]
Add this package to composer.json require line: 

`"cagartner/phpquery": "0.9.8"`

`"require": {
        "php": ">=5.1.0",
        "tcesarpinho/php-sigep": ">=0.0.1",
        "cagartner/phpquery": "0.9.8"
    },`
