### ISSUE TITLE
Erro no magento após instalação

### ISSUE THREAD

**Issue by lffruhling** [Bleez/Bleez-Correios#12]
Até aqui tudo bem

"composer require bleez/correios
php bin/magento module:enable --clear-static-content Bleez_Correios
php bin/magento setup:upgrade"

Agora neste último comando.
php bin/magento setup:static-content:deploy.

retorna que existe um erro
Successful: 2393 files; errors: 1
 e não funciona mais o magento...

**Comment by frmichetti** [comment]
Aconteceu o mesmo comigo.
eu reverti com os comandos:

1 - composer remove bleez/correios
2 - chmod 777 magento/ -R (liberei as permissões novamente)
3 - php bin/magento setup:upgrade

 e parou com o erro 500..

**Comment by tcesarpinho** [comment]
Desculpa a demora em responder, testei aqui com a versão 2.1.4 e funcionou normalmente vocês podem colar os log que estão na pasta var/log e os reports da var/reports para descobrir o que aconteceu? qual a versão do php de vcs?

**Comment by lffruhling** [comment]
resolvi com o $ chown www-data:www-data /meu_diretorio/ -R

era questão de permissão

**Comment by albertobraschi** [comment]
Estou com um issue na versão 2.1.2 

[2018-01-18 19:31:29] main.CRITICAL: Exception: Notice: Undefined index: product in ~/public_html/vendor/bleez/correios/Model/Consulta.php on line 153 in ~/public_html/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 ~/public_html/vendor/bleez/correios/Model/Consulta.php(153): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '~/...', 153, Array)
#1 [internal function]: Bleez\Correios\Model\Consulta->estimarFrete()
#2 ~/public_html/vendor/magento/module-webapi/Controller/Rest.php(307): call_user_func_array(Array, Array)
#3 ~/public_html/vendor/magento/module-webapi/Controller/Rest.php(216): Magento\Webapi\Controller\Rest->processApiRequest()
#4 ~/public_html/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(37): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#5 ~/public_html/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#6 ~/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#7 ~/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#8 {main}

Next Exception: Report ID: webapi-5a60f6118b1a6; Message: Notice: Undefined index: product in ~/public_html/vendor/bleez/correios/Model/Consulta.php on line 153 in ~/public_html/vendor/magento/framework/Webapi/ErrorProcessor.php:195
Stack trace:
#0 ~/public_html/vendor/magento/framework/Webapi/ErrorProcessor.php(139): Magento\Framework\Webapi\ErrorProcessor->_critical(Object(Exception))
#1 ~/public_html/vendor/magento/module-webapi/Controller/Rest.php(219): Magento\Framework\Webapi\ErrorProcessor->maskException(Object(Exception))
#2 ~/public_html/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(37): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#3 ~/public_html/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#4 ~/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#5 ~/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#6 {main} [] []
