### ISSUE TITLE
Volume total completamente errado

### ISSUE THREAD

**Issue by sergiomendonca** [Bleez/Bleez-Correios#42]
O plugin está desprezando altura, largura e comprimento.
Quando tem os 3 ele faz o somatorio de todas as arestas para depois multiplicar uma pela outra..
NÃO É ASSIM QUE CALCULA VOLUME.

**Comment by sergiomendonca** [comment]
Consertei:

**Comment by katiakweb** [comment]
Como, Sergio Mendonça?

**Comment by sergiomendonca** [comment]
**Assim: https://github.com/Bleez/Bleez-Correios/issues/41**

Que tipo de produto você vende? As vezes nem compensa mexer.

Eu preciso porque trabalho com coisas mais pesadas e ficar sem o calculo de volume fazia tomar prejuízo constantemente.

Ele fazia o somatorio de volume de todas as arestas, veja como fica errado:


Imagina que você tem duas caixas de 15x15x15.

caixa 1 Volume total: 3375

caixa 2 Volume total: 3375

Volume final das duas caixas: 6750

Como está o codigo dele atualmente?

Alem de nao obter altura,comprimento e largura corretamente ele fazia o somatorio de cada aresta e ficava dessa forma:

(15+15)x(15+15)x(15+15)  = 27000!

Passou bem longe esse calculo.

O que fiz foi somar o volume total e tirar a raiz cubica.

15x15x15 = 6750

y3 = 6750

y = 15. e ai eu informa altura = 15, lagura = 15 e comprimento = 15.

Isso se faz necessario porque ele passa altura, largura e comprimento no algoritmo e nao o volume total.

E assim a precisão aumentou.

Se tiver duvidas só falar.

Esse questão ai do **"foreach"** que eu fiz é porque o magento duplica o produto->getAllItens quando temos produtos configuraveis(Um erro antigaço do magento...). Fonte(https://stackoverflow.com/questions/7877566/magento-order-getallitems-return-twice-the-same-item)
