### ISSUE TITLE
Erro no checkout quando mudo o CEP Notice: Undefined property: stdClass::$complemento in vendor/tcesarpinho/php-sigep/src/PhpSigep/Services/Real/ConsultaCep.php on line 38

### ISSUE THREAD

**Issue by backendorf** [Bleez/Bleez-Correios#43]
Notice: Undefined property: stdClass::$complemento in /vendor/tcesarpinho/php-sigep/src/PhpSigep/Services/Real/ConsultaCep.php on line 38

**Comment by marcosdsdba** [comment]
Comente as linhas 38,39 e 41:

             if (property_exists($r, 'return') && $r->return instanceof \stdClass) {
                $consultaCepResposta = new ConsultaCepResposta();
                $consultaCepResposta->setBairro(SoapClientFactory::convertEncoding($r->return->bairro));
                $consultaCepResposta->setCep($r->return->cep);
                $consultaCepResposta->setCidade(SoapClientFactory::convertEncoding($r->return->cidade));
//                $consultaCepResposta->setComplemento1(SoapClientFactory::convertEncoding($r->return->complemento));
//                $consultaCepResposta->setComplemento2(SoapClientFactory::convertEncoding($r->return->complemento2));
                $consultaCepResposta->setEndereco(SoapClientFactory::convertEncoding($r->return->end));
//                $consultaCepResposta->setId($r->return->id);
                $consultaCepResposta->setUf($r->return->uf);
                $result->setResult($consultaCepResposta);

Retorno original dessa chamada é :

   [return] => stdClass Object
        (
            [bairro] => Ingleses do Rio Vermelho
            [cep] => 88058327
            [cidade] => Florian &oacute;polis
            [complemento] =>
            [complemento2] =>
            [id] =>
            [end] => Servid&atilde;o Ayrton Senna
            [uf] => SC
        )

)
